In [52]:
import requests
import pandas as pd

In [6]:
data_url = 'https://inf553-220b8.firebaseio.com/project/matches.json'

data = requests.get(data_url)
data_json = data.json()

In [78]:
# gameDuration gameId  participants  teams
column = ['gameId','gameDuration','championId','assists','kills','damageDealtToObjectives','damageDealtToTurrets',
         'damageSelfMitigated','deaths','goldEarned','totalDamageDealtToChampions','trueDamageDealt','if_win','lane']
gameids_ls, gametime_ls, champid_ls,assist_ls, kill_ls,dm_t_ob_ls = [],[],[],[],[],[]
dm_t_tt_ls,dm_mt_ls,death_ls,gold_ls,tot_da_ls,tr_dm_ls,win_ls,lane_ls=  [],[],[],[],[],[],[],[]

champions_pd = pd.DataFrame(columns=column)

In [84]:
for match in list(data_json.values()):    
    for i in range(10):
        try:
            gameId = match['gameId']
            gameDuration = match['gameDuration']
            championId = match['participants'][i]['championId']
            assists = match['participants'][i]['stats']['assists']
            kills = match['participants'][i]['stats']['kills']
            damageDealtToObjectives = match['participants'][i]['stats']['damageDealtToObjectives']
            damageDealtToTurrets =  match['participants'][i]['stats']['damageDealtToTurrets']
            damageSelfMitigated = match['participants'][i]['stats']['damageSelfMitigated']
            deaths = match['participants'][i]['stats']['deaths'] * -1
            goldEarned = match['participants'][i]['stats']['goldEarned']
            totalDamageDealtToChampions = match['participants'][i]['stats']['totalDamageDealtToChampions']
            trueDamageDealt = match['participants'][i]['stats']['trueDamageDealt']
            if_win = match['participants'][i]['stats']['win']
            lane = match['participants'][i]['timeline']['lane']

            gameids_ls.append(gameId)
            gametime_ls.append(gameDuration)
            champid_ls.append(championId)
            assist_ls.append(assists)
            kill_ls.append(kills)
            dm_t_ob_ls.append(damageDealtToObjectives)
            dm_t_tt_ls.append(damageDealtToTurrets)
            dm_mt_ls.append(damageSelfMitigated)
            death_ls.append(deaths)
            gold_ls.append(goldEarned)
            tot_da_ls.append(totalDamageDealtToChampions)
            tr_dm_ls.append(trueDamageDealt)
            win_ls.append(int(if_win))
            lane_ls.append(lane)
        except:
            continue

In [68]:
gameId = match['gameId']
gameDuration = match['gameDuration']
championId = match['participants'][0]['championId']
assists = match['participants'][0]['stats']['assists']
kills = match['participants'][0]['stats']['kills']
damageDealtToObjectives = match['participants'][0]['stats']['damageDealtToObjectives']
damageDealtToTurrets =  match['participants'][0]['stats']['damageDealtToTurrets']
damageSelfMitigated = match['participants'][0]['stats']['damageSelfMitigated']
deaths = match['participants'][0]['stats']['deaths'] * -1
goldEarned = match['participants'][0]['stats']['goldEarned']
totalDamageDealtToChampions = match['participants'][0]['stats']['totalDamageDealtToChampions']
trueDamageDealt = match['participants'][0]['stats']['trueDamageDealt']
if_win = match['participants'][0]['stats']['win']
lane = match['participants'][0]['timeline']['lane']

In [85]:
champions_pd.gameId = gameids_ls; champions_pd.gameDuration = gametime_ls
champions_pd.championId = champid_ls; champions_pd.assists = assist_ls
champions_pd.kills = kill_ls; champions_pd.damageDealtToObjectives = dm_t_ob_ls
champions_pd.damageDealtToTurrets = dm_t_tt_ls; champions_pd.damageSelfMitigated = dm_mt_ls
champions_pd.deaths = death_ls;champions_pd.goldEarned = gold_ls
champions_pd.totalDamageDealtToChampions = tot_da_ls;champions_pd.trueDamageDealt = tr_dm_ls
champions_pd.if_win = win_ls;champions_pd.lane = lane_ls

In [88]:
champions_pd

,gameId,gameDuration,championId,assists,kills,damageDealtToObjectives,damageDealtToTurrets,damageSelfMitigated,deaths,goldEarned,totalDamageDealtToChampions,trueDamageDealt,if_win,lane
0,3017019005,1807,92,1,2,15514,4156,16343,-3,10173,7761,18615,1,TOP
1,3017019005,1807,268,6,7,10747,6700,8507,-5,12013,24507,1924,1,MIDDLE
2,3017019005,1807,143,16,2,3867,1249,4562,-8,8896,20770,1219,1,BOTTOM
3,3017019005,1807,59,16,10,31144,2368,22353,-2,14153,18042,11569,1,JUNGLE
4,3017019005,1807,15,14,8,19962,9972,7533,-4,12849,21531,2987,1,BOTTOM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66256,3608223245,1036,202,18,13,716,716,8361,-7,12262,16898,2887,1,NONE
66257,3608223245,1036,145,20,12,1309,1309,9788,-4,11747,29875,0,1,NONE
66258,3608223245,1036,37,32,8,2010,2010,13650,-5,11635,11864,547,1,NONE
66259,3608223245,1036,115,21,8,2227,2227,4071,-5,11412,20756,0,1,NONE
66260,3608223245,1036,114,11,4,1725,1725,25004,-8,9933,11050,2853,1,NONE

In [90]:
champions_pd.to_csv('champion.csv',index=None)

In [99]:
champion_file = '../data/championFull.json'
with open(champion_file) as f:
    champs = json.load(f) 
# what we need is champs['data']  champs['keys']
champ_id_name = champs['keys'] 
all_champion_data = champs['data']
champion_item = {}

for k,v in all_champion_data.items():
    id_= int(v['key'])
    name = v['name'] 
    champion_item[id_] = name

In [103]:
ids = list(champions_pd.championId)
names = []
for id_ in ids:
    names.append(champion_item[id_])

In [105]:
champions_pd['name'] = names

In [106]:
champions_pd

,gameId,gameDuration,championId,assists,kills,damageDealtToObjectives,damageDealtToTurrets,damageSelfMitigated,deaths,goldEarned,totalDamageDealtToChampions,trueDamageDealt,if_win,lane,name
0,3017019005,1807,92,1,2,15514,4156,16343,-3,10173,7761,18615,1,TOP,Riven
1,3017019005,1807,268,6,7,10747,6700,8507,-5,12013,24507,1924,1,MIDDLE,Azir
2,3017019005,1807,143,16,2,3867,1249,4562,-8,8896,20770,1219,1,BOTTOM,Zyra
3,3017019005,1807,59,16,10,31144,2368,22353,-2,14153,18042,11569,1,JUNGLE,Jarvan IV
4,3017019005,1807,15,14,8,19962,9972,7533,-4,12849,21531,2987,1,BOTTOM,Sivir
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66256,3608223245,1036,202,18,13,716,716,8361,-7,12262,16898,2887,1,NONE,Jhin
66257,3608223245,1036,145,20,12,1309,1309,9788,-4,11747,29875,0,1,NONE,Kai'Sa
66258,3608223245,1036,37,32,8,2010,2010,13650,-5,11635,11864,547,1,NONE,Sona
66259,3608223245,1036,115,21,8,2227,2227,4071,-5,11412,20756,0,1,NONE,Ziggs
66260,3608223245,1036,114,11,4,1725,1725,25004,-8,9933,11050,2853,1,NONE,Fiora